require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/blends", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Blend. As you add validations to Blend, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Blend.create! valid_attributes
      get blends_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      blend = Blend.create! valid_attributes
      get blend_url(blend)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_blend_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      blend = Blend.create! valid_attributes
      get edit_blend_url(blend)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Blend" do
        expect {
          post blends_url, params: { blend: valid_attributes }
        }.to change(Blend, :count).by(1)
      end

      it "redirects to the created blend" do
        post blends_url, params: { blend: valid_attributes }
        expect(response).to redirect_to(blend_url(Blend.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Blend" do
        expect {
          post blends_url, params: { blend: invalid_attributes }
        }.to change(Blend, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post blends_url, params: { blend: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blend" do
        blend = Blend.create! valid_attributes
        patch blend_url(blend), params: { blend: new_attributes }
        blend.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the blend" do
        blend = Blend.create! valid_attributes
        patch blend_url(blend), params: { blend: new_attributes }
        blend.reload
        expect(response).to redirect_to(blend_url(blend))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        blend = Blend.create! valid_attributes
        patch blend_url(blend), params: { blend: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested blend" do
      blend = Blend.create! valid_attributes
      expect {
        delete blend_url(blend)
      }.to change(Blend, :count).by(-1)
    end

    it "redirects to the blends list" do
      blend = Blend.create! valid_attributes
      delete blend_url(blend)
      expect(response).to redirect_to(blends_url)
    end
  end
end
