require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/blend_logs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BlendLog. As you add validations to BlendLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BlendLog.create! valid_attributes
      get blend_logs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      blend_log = BlendLog.create! valid_attributes
      get blend_log_url(blend_log)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_blend_log_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      blend_log = BlendLog.create! valid_attributes
      get edit_blend_log_url(blend_log)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BlendLog" do
        expect {
          post blend_logs_url, params: { blend_log: valid_attributes }
        }.to change(BlendLog, :count).by(1)
      end

      it "redirects to the created blend_log" do
        post blend_logs_url, params: { blend_log: valid_attributes }
        expect(response).to redirect_to(blend_log_url(BlendLog.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BlendLog" do
        expect {
          post blend_logs_url, params: { blend_log: invalid_attributes }
        }.to change(BlendLog, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post blend_logs_url, params: { blend_log: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blend_log" do
        blend_log = BlendLog.create! valid_attributes
        patch blend_log_url(blend_log), params: { blend_log: new_attributes }
        blend_log.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the blend_log" do
        blend_log = BlendLog.create! valid_attributes
        patch blend_log_url(blend_log), params: { blend_log: new_attributes }
        blend_log.reload
        expect(response).to redirect_to(blend_log_url(blend_log))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        blend_log = BlendLog.create! valid_attributes
        patch blend_log_url(blend_log), params: { blend_log: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested blend_log" do
      blend_log = BlendLog.create! valid_attributes
      expect {
        delete blend_log_url(blend_log)
      }.to change(BlendLog, :count).by(-1)
    end

    it "redirects to the blend_logs list" do
      blend_log = BlendLog.create! valid_attributes
      delete blend_log_url(blend_log)
      expect(response).to redirect_to(blend_logs_url)
    end
  end
end
